apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restricted-view-binding
subjects:
- kind: User
  name: sameer # Replace with the actual username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: restricted-view
  apiGroup: rbac.authorization.k8s.io

