cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jdoe:
      email: jdoe@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: John Doe
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
    stest:
      email: sankettest@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Sanket Test
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
    stest2:
      email: sankettest@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Sanket Test
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$uNaTgvGPG9rMbzOJHYaPQePw0DUfp1qHBrSq6l4O304qani6pKFpm
pre-authorized:
  emails:
    - melsby@gmail.com